language: python
sudo: false
python: 2.7
env:
  global:
    PYTHONUNBUFFERED=yes
  matrix:
    - TOXENV=2.7
    - TOXENV=3.3
    - TOXENV=3.4
    - TOXENV=pypy
    - TOXENV=pypy3
install:
  - pip install tox
  - pip install coveralls
script:
  - tox
after_success:
  - coveralls