language: python
sudo: false
python: 2.7
env:
  global:
    PYTHONUNBUFFERED=yes
  matrix:
    - TOXENV=py2.7-dj1.7
    - TOXENV=py2.7-dj1.8
    - TOXENV=py2.7-dj1.9
    - TOXENV=py3.3-dj1.7
    - TOXENV=py3.3-dj1.8
    - TOXENV=py3.4-dj1.7
    - TOXENV=py3.4-dj1.8
    - TOXENV=py3.4-dj1.9
    - TOXENV=py3.5-dj1.8
    - TOXENV=py3.5-dj1.9    
    - TOXENV=pypy-dj1.7
    - TOXENV=pypy-dj1.8
    - TOXENV=pypy-dj1.9
    - TOXENV=pypy3-dj1.7
    - TOXENV=pypy3-dj1.8
    - TOXENV=cov
install:
  - pip install tox
  - pip install coveralls
script:
  - tox
after_success:
  - coveralls